### ISSUE TITLE
This package is not OSI compliant libre software

### ISSUE THREAD

**Issue by jengelh** [gap-packages/modisom#10] opened 2018-11-15 00:02 UTC
The `COPYRIGHT` file states:

"""You are free to use the programs and distribute them, provided
you do not change them"""

Ability to change is one of the essential freedoms of common free/libre software projects, but this project does not give it.

**Comment by alex-konovalov** [comment] 2018-11-15 10:53
Thanks @jengelh - I am not an author of this package, only a maintainer. I will check with the author. However, your comment in fact neither explains what the problem is (i.e. which obstacle it creates to your project), nor suggests a suitable solution. It only states the fact which is certainly already known to the author, and I respect their wish to choose this type of the license, even though my software is licensed differently. I think the author may find it helpful if you could provide some more context.

**Comment by jengelh** [comment] 2018-11-15 11:52
>neither explains what the problem is (i.e. which obstacle it creates to your project),

The problem is that 

1. this github repository is distributing modified source code, which is against the present licensing terms,
1. anyone cloning or redistributing the git tree would incur the same issue,
1. the original unmodified modisom (i.e. first commit in the git repo), though redistributable, will in general not be acceptable by e.g. Linux distributions because they often only accept code with certain freedoms (such as the permission to modify and distribute modified copies),
1. modisom is an officially endorsed GAP package (https://www.gap-system.org/Releases/index.html), and I would like to see it shipped in one or more Linux distros if so possible.

>suggests a suitable solution.

The options would be

1. to obtain appropriate permissions from the original author(s) to basically "use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies" (these poignant terms appear in https://spdx.org/licenses/MIT.html , but they are also an element of other licenses such as the GPL)
1. dropping modisom

**Comment by alex-konovalov** [comment] 2018-11-15 12:29
I don't really understand 1 and 2. Modifications in this code are made with the agreement from authors/maintainers. This does not prevent anyone from cloning the repository. The same with 3. Are you trying to say that the authors can't modify their own code and make new releases?

About 4, are you speaking about Linux distros in general, or do you represent a particular distro? If so, which licenses it accepts? For example, what about https://opensource.org/licenses/Artistic-2.0 ?

Side remark: I don't really find reliable the approach to redistribute GAP packages as individual Linux distro packages. For each release, we carefully test carefully sets of packages to work together and to be compatible with GAP. If the users will end up with a different selection of packages, some updated, some not, it's hard to guarantee that it will work in the same way.

**Comment by jengelh** [comment] 2018-11-15 13:35
>Modifications in this code are made with the agreement from authors/maintainers.

Well ok. But that agreement is just between you and the original copyright holder — the general public is still excluded from modification as per the contents of the COPYRIGHT file.

**Comment by alex-konovalov** [comment] 2018-11-16 13:59
Well, I am sure that the author is aware of this. To reconsider, it will be useful if you do will reply on my direct question about point 4: is artistic license ok for the project that you work on?

**Comment by alex-konovalov** [comment] 2018-12-05 12:42
We agreed to make the next release under the GPL v2 license. I will check if there are any other changes that can be made for the next release.

**Comment by alex-konovalov** [comment] 2019-02-19 13:02
Closed in d86c7af1ae551fbc9adb827ddae6f003f1fa5bb1, releases as version 2.5.0

**Closed by alex-konovalov** 2019-02-19 13:02 UTC
